on: [push]

name: EngineeringScoreCard

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure CLI Action
        id: psscript
        shell: powershell
        run: |
          $result = &".\TestOutput.ps1"
          echo "::set-output name=res::$result"
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.SNANKANI_PRIVATE_PAT }}

      - name: Check outputs
        id: checkoutput
        run: echo ${{ steps.psscript.outputs.res }}
