on: [push, issues]

name: EngineeringScoreCard

jobs:
  build-and-deploy:
    runs-on: windows
    steps:
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az -h
            az extension add --name azure-devops
            az devops -h
            az devops project list --org https://dev.azure.com/mseng
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.SNANKANI_PRIVATE_PAT }}
