on: [issues]

name: EngineeringScoreCard

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account show
            az storage -h
