on:
  #schedule:
  #  - cron: "* 9 * * *"
  repository_dispatch:
    types: [servicecatalogscorecard]

name: Service Catalog Scorecard

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: fetch scorecard
        id: issues
        run: echo ::set-output name=SCORECARD::$(curl -sb -D- -u ${{secrets.ACCESS_TOKEN}} -X POST  -H "Content-Type:application/json" -d '{ {  { maintainer { name }}} }' https://catalog-staging.githubapp.com/graphql)
